### ISSUE TITLE
相机通过ehome协议注册成功，如何取流

### ISSUE THREAD

**Issue by szpebble** [tsingeye/FreeEhome#12]
相机通过ehome协议注册成功，如何取流rtsp/rtmp?

**Comment by scdn** [comment]
感觉只是想卖自己的产品，并非有意开源

**Comment by tsingeye** [comment]
> 感觉只是想卖自己的产品，并非有意开源

你看到卖啥产品了？

**Comment by scdn** [comment]
> > 感觉只是想卖自己的产品，并非有意开源
> 
> 你看到卖啥产品了？

有没有你比我更清楚
本身赚钱很正常
但是又当又立就很恶心
