### ISSUE TITLE
国标平台支持28181和Ehome 预览地址：https://wzciot.site/

### ISSUE THREAD

**Issue by WWTBNBWN** [tsingeye/FreeEhome#13]
国标平台支持28181和Ehome 预览地址：https://wzciot.site/ Java+tdui 保持更新  wx:WYWZC888666

**Comment by tsingeye** [comment]
> 国标平台支持28181和Ehome 预览地址：https://wzciot.site/ Java+tdui 保持更新 wx:WYWZC888666

开源出来吧， 比你这么获客效果要好
