### ISSUE TITLE
人脸识别门禁机通过ehome注册到FreeEhomeCMS后，门禁机变更ip，后台调用设备信息接口，仍然是旧ip

### ISSUE THREAD

**Issue by cinos1** [tsingeye/FreeEhome#7]
问题如标题，只有在手动重启人脸识别设备，后台才会收到新的消息，否则后台获取仍然是旧ip
·`2022-03-16 12:01:01 Receive register request, DeviceID=mytest, DeviceIP=192.168.3.186
2022-03-16 12:01:11 DeviceID=mytest reconnected successfully, closed the old keepalive goroutine`
请问此问题如何解决？谢谢！

**Comment by tsingeye** [comment]
后台数据库没有修改ip，自行根据需求来修改吧
