### ISSUE TITLE
如果软件部署到云上面，流媒体SMS地址务必写公网IP，否则startStream时报401

### ISSUE THREAD

**Issue by bitilly** [tsingeye/FreeEhome#8]
![1647850023](https://user-images.githubusercontent.com/34022137/159223746-c8deff4d-10a5-4ebc-9263-35496a0aa6d1.jpg)

**Comment by bitilly** [comment]
程序是部署到云上面的

**Comment by tsingeye** [comment]
视频格式是265还是264？

**Comment by bitilly** [comment]
> 视频格式是265还是264？

感谢回复，通过查看日志，问题已经解决了。

因为是部署到云上面，所以这块配置应该写公网IP

#流媒体SMS地址
streamStartIP = "192.168.1.111"

**Comment by bitilly** [comment]
感谢回复，通过查看日志，问题已经解决了。
因为是部署到云上面，所以这块配置应该写公网IP
#流媒体SMS地址
streamStartIP = "192.168.1.111"



***@***.***
 
发件人： Luke
发送时间： 2022-03-22 14:11
收件人： tsingeye/FreeEhome
抄送： bitilly; Author
主题： Re: [tsingeye/FreeEhome] 请问这个是什么原因？启动视频失败，日志如下：401 (Issue #8)
视频格式是265还是264？
