### ISSUE TITLE
能加上历史回放功能么？

### ISSUE THREAD

**Issue by bitilly** [tsingeye/FreeEhome#9]

**Comment by tsingeye** [comment]
回放需要用到海康的解码库，解码库需要海康授权才能使用，所以目前无法增加。

**Comment by bitilly** [comment]
好的



***@***.***
 
发件人： Luke
发送时间： 2022-03-23 10:46
收件人： tsingeye/FreeEhome
抄送： bitilly; Author
主题： Re: [tsingeye/FreeEhome] 能加上历史回放功能么？ (Issue #9)
回放需要用到海康的解码库，解码库需要海康授权才能使用，所以目前无法增加。
